"""added colums to user table

Revision ID: 3c8a72f6f97c
Revises: 39b762fa91ca
Create Date: 2019-03-29 22:38:14.902253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8a72f6f97c'
down_revision = '39b762fa91ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed_on')
    op.drop_column('user', 'email_confirmed')
    op.drop_column('user', 'email_confirmation_sent_on')
    op.drop_column('user', 'authenticated')
    # ### end Alembic commands ###
