"""empty message

Revision ID: 853d3c580bae
Revises: e4cd5c06c9e2
Create Date: 2019-04-05 23:26:41.585092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853d3c580bae'
down_revision = 'e4cd5c06c9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'post_id')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('post_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
