"""added extra column in user table

Revision ID: bc1cb8446324
Revises: 0c4eff58dfe9
Create Date: 2019-04-02 15:38:05.379908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1cb8446324'
down_revision = '0c4eff58dfe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_logged_in', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_logged_in')
    # ### end Alembic commands ###
